name: deploy to lambda
on:
  push:
    branches: main

jobs:
  deploy_source:
    name: deploy lambda from source
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: zip lambda.zip index.mjs
      - uses: yvesgurcan/deploy-lambda-function@v0.0.5
        with:
          AWS_SECRET_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-west-1
          function-name: whoseTurnIsIt
          package: lambda.zip
